// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "name": "AlAA AYAAD",
  "welcome": "Welcome to my Next.js application",
  "description": "This is a multilingual application built with Next.js and next-intl",
  "switchLanguage": "Switch Language"
};
export default messages;