import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/ui/footer/Footer";
import { ContactusContext } from "@/components/context/ContactusContext";
import "aos/dist/aos.css";
import WithAOS from "@/components/withaos/WithAos";
const InterFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Gonovo Company",
  icons: "/svgs/logo.svg",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ContactusContext>
        <body className={`${InterFont.variable}`}>
          <WithAOS>
            {children}
            <Footer />
          </WithAOS>
        </body>
      </ContactusContext>
    </html>
  );
}
